services:
  node1:
    build: .
    command: ["node1", "8001"]
    ports:
      - "8001:8001"
      - "9001:9001"
  node2:
    build: .
    command: ["node2", "8002"]
    ports:
      - "8002:8002"
      - "9002:9002"
  node3:
    build: .
    command: ["node3", "8003"]
    ports:
      - "8003:8003"
      - "9003:9003"
  node4:
    build: .
    command: ["node4", "8004"]
    ports:
      - "8004:8004"
      - "9004:9004"
  node5:
    build: .
    command: ["node5", "8005"]
    ports:
      - "8005:8005"
      - "9005:9005"
